repos:
  # 1. 先运行代码格式化工具
  - repo: https://github.com/zhouzaida/isort
    rev: 5.12.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--style=.style.yapf]

  # 2. 最后运行代码检查工具
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  # 其他钩子保持原顺序
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args: [--ignore-words-list=ba,adress,datas]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)^(
              dicts/|
              projects/.*?/dicts/
            )
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
              dicts/|
              projects/.*?/dicts/
            )
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
